# Generated by Django 5.2.5 on 2025-08-23 04:59

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', markdownx.models.MarkdownxField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubs.article')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pubs.article')),
                ('active_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Active_version', to='pubs.publication')),
                ('last_valid_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Last_valid_version', to='pubs.publication')),
            ],
        ),
    ]
