# Generated by Django 5.2.5 on 2025-08-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0003_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='plain_text',
            field=models.TextField(default=''),
        ),
    ]
